version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    image: grpcweb/envoy
    env_file:
      - dev.env
    ports:
      - "8001:8001"
      - "8501:8501"
    networks:
      - fullstack-network

  # bazel:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile-dev
  #     args:
  #       - USER_ID=${USER_ID}
  #       - GROUP_ID=${GROUP_ID}
  #   image: dev/bazel
  #   user: "${USER_ID}:${GROUP_ID}"
  #   entrypoint: /bin/sh
  #   command: "-c 'sleep infinity'"
  #   env_file:
  #     - dev.env
  #   ports:
  #     - "6001:6001"
  #     - "6002:6002"
  #     - "7001:7001"
  #   volumes:
  #     - ~/.cache/bazel-disk-cache:/root/.cache/bazel-disk-cache
  #     - ../../:/home/workspace
  #   networks:
  #     - fullstack-network

  ibazel:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    image: dev/ibazel
    command: "build //..."
 
  service1:
    image: dev/ibazel
    command: "run //src/backend/service1"
    depends_on:
      - ibazel
    env_file:
      - dev.env
    ports:
      - "6001:6001"
    volumes:
      - ~/.cache/bazel-disk-cache:/root/.cache/bazel-disk-cache
      - ../../:/home/workspace
    networks:
      - fullstack-network

  service2:
    image: dev/ibazel
    command: "run //src/backend/service2"
    depends_on:
      - service1
      - ibazel
    env_file:
      - dev.env
    ports:
      - "6002:6002"
    volumes:
      - ~/.cache/bazel-disk-cache:/root/.cache/bazel-disk-cache
      - ../../:/home/workspace
    networks:
      - fullstack-network

  dashboard:
    image: dev/ibazel
    command: "run //src/frontend/dashboard:devserver"
    depends_on:
      - service1
      - ibazel
    env_file:
      - dev.env
    ports:
      - "7001:7001"
    volumes:
      - ~/.cache/bazel-disk-cache:/root/.cache/bazel-disk-cache
      - ../../:/home/workspace
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
